"""Weekly report generation for commercial intelligence."""

import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from analytics.analyzer import CommercialAnalyzer


class WeeklyReportGenerator:
    def __init__(self):
        self.analyzer = CommercialAnalyzer()
        self.report_date = datetime.now().strftime("%Y-%m-%d")

    def generate_html_report(self) -> str:
        """Generate HTML weekly report."""
        bookings = self.analyzer.get_booking_trends(days=7)
        sources = self.analyzer.get_booking_sources()
        ads = self.analyzer.get_ad_performance(days=7)
        social = self.analyzer.get_social_engagement()
        roi = self.analyzer.get_roi_summary(days=7)

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Equester Commercial Intelligence Report - {self.report_date}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
                .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }}
                h1 {{ color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }}
                h2 {{ color: #555; margin-top: 30px; }}
                .metric {{ display: inline-block; margin: 10px 20px 10px 0; padding: 15px; background: #f9f9f9; border-radius: 5px; border-left: 4px solid #007bff; }}
                .metric-value {{ font-size: 24px; font-weight: bold; color: #007bff; }}
                .metric-label {{ font-size: 12px; color: #666; margin-top: 5px; }}
                table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
                th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background: #007bff; color: white; }}
                tr:hover {{ background: #f5f5f5; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>📊 Equester Commercial Intelligence Report</h1>
                <p>Generated: {self.report_date}</p>

                <h2>💰 Revenue & Bookings</h2>
                <div>
                    <div class="metric">
                        <div class="metric-value">{len(bookings)}</div>
                        <div class="metric-label">Bookings (7 days)</div>
                    </div>
                </div>

                <h2>📢 Advertising Performance</h2>
                <div>
                    <div class="metric">
                        <div class="metric-value">AED {ads['meta_ads'].get('spend', 0):.2f}</div>
                        <div class="metric-label">Meta Ad Spend</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">AED {ads['google_ads'].get('spend', 0):.2f}</div>
                        <div class="metric-label">Google Ad Spend</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">AED {roi['roi']:.1f}%</div>
                        <div class="metric-label">ROI (7 days)</div>
                    </div>
                </div>

                <h2>📱 Social Media Engagement</h2>
                <div>
                    <div class="metric">
                        <div class="metric-value">{social['instagram'].get('posts', 0)}</div>
                        <div class="metric-label">Instagram Posts</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">{social['facebook'].get('posts', 0)}</div>
                        <div class="metric-label">Facebook Posts</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">{social['tiktok'].get('videos', 0)}</div>
                        <div class="metric-label">TikTok Videos</div>
                    </div>
                </div>

                <h2>Booking Sources</h2>
                <table>
                    <tr>
                        <th>Source</th>
                        <th>Bookings</th>
                        <th>Revenue (AED)</th>
                    </tr>
                    {''.join(f"<tr><td>{row['booking_source']}</td><td>{row['count']}</td><td>AED {row['revenue_aed']:.2f}</td></tr>"
                      for _, row in sources.iterrows())}
                </table>

                <p style="color: #999; font-size: 12px; margin-top: 30px;">
                    This report was automatically generated by the Equester Commercial Intelligence Pipeline.
                </p>
            </div>
        </body>
        </html>
        """
        return html

    def save_report(self, filename: str = None) -> str:
        """Save report to file."""
        if filename is None:
            filename = f"report_{self.report_date}.html"

        report_dir = Path(__file__).parent
        filepath = report_dir / filename

        html_content = self.generate_html_report()
        with open(filepath, "w") as f:
            f.write(html_content)

        print(f"Report saved to {filepath}")
        return str(filepath)


if __name__ == "__main__":
    generator = WeeklyReportGenerator()
    generator.save_report()
